version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: code-analysis-neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_memory_pagecache_size=2G
      - NEO4J_dbms_query_timeout=5m
      - NEO4J_dbms_transaction_timeout=10m
      - NEO4J_dbms_logs_query_enabled=true
      - NEO4J_dbms_logs_query_threshold=1s
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - code-analysis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: code-analysis-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - code-analysis
    restart: unless-stopped

  mcp-server:
    build: .
    container_name: code-analysis-mcp
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - NODE_ENV=production
      - LOG_LEVEL=info
    ports:
      - "3000:3000"
      - "9090:9090"
    volumes:
      - ./logs:/app/logs
      - ./cache:/app/cache
      - /tmp:/tmp
    depends_on:
      - neo4j
      - redis
    networks:
      - code-analysis
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: code-analysis-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - code-analysis
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: code-analysis-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    networks:
      - code-analysis
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  code-analysis:
    driver: bridge